#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sane-backends
Version  : 1.0.27
Release  : 2
URL      : https://alioth.debian.org/frs/download.php/file/4224/sane-backends-1.0.27.tar.gz
Source0  : https://alioth.debian.org/frs/download.php/file/4224/sane-backends-1.0.27.tar.gz
Summary  : Backends for SANE, the universal scanner interface
Group    : Development/Tools
License  : GPL-2.0
Requires: sane-backends-bin
Requires: sane-backends-lib
Requires: sane-backends-doc
Requires: sane-backends-locales
BuildRequires : ghostscript
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(libv4l1)
BuildRequires : systemd-dev

%description
How to configure, build, and install SANE.
Introduction:
=============
SANE stands for Scanner Access Now Easy.
This package contains the SANE libraries (this means backends and
network scanning parts) and the command line frontend scanimage.
You always find the most recent version of SANE on:

%package bin
Summary: bin components for the sane-backends package.
Group: Binaries

%description bin
bin components for the sane-backends package.


%package dev
Summary: dev components for the sane-backends package.
Group: Development
Requires: sane-backends-lib
Requires: sane-backends-bin
Provides: sane-backends-devel

%description dev
dev components for the sane-backends package.


%package doc
Summary: doc components for the sane-backends package.
Group: Documentation

%description doc
doc components for the sane-backends package.


%package lib
Summary: lib components for the sane-backends package.
Group: Libraries

%description lib
lib components for the sane-backends package.


%package locales
Summary: locales components for the sane-backends package.
Group: Default

%description locales
locales components for the sane-backends package.


%prep
%setup -q -n sane-backends-1.0.27

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523660667
%configure --disable-static --disable-avahi
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1523660667
rm -rf %{buildroot}
%make_install
%find_lang sane-backends

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gamma4scanimage
/usr/bin/sane-config
/usr/bin/sane-find-scanner
/usr/bin/saned
/usr/bin/scanimage
/usr/bin/umax_pp

%files dev
%defattr(-,root,root,-)
/usr/include/sane/sane.h
/usr/include/sane/saneopts.h
/usr/lib64/libsane.so
/usr/lib64/pkgconfig/sane-backends.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/sane\-backends/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man7/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsane.so.1
/usr/lib64/libsane.so.1.0.27
/usr/lib64/sane/libsane-abaton.so
/usr/lib64/sane/libsane-abaton.so.1
/usr/lib64/sane/libsane-abaton.so.1.0.27
/usr/lib64/sane/libsane-agfafocus.so
/usr/lib64/sane/libsane-agfafocus.so.1
/usr/lib64/sane/libsane-agfafocus.so.1.0.27
/usr/lib64/sane/libsane-apple.so
/usr/lib64/sane/libsane-apple.so.1
/usr/lib64/sane/libsane-apple.so.1.0.27
/usr/lib64/sane/libsane-artec.so
/usr/lib64/sane/libsane-artec.so.1
/usr/lib64/sane/libsane-artec.so.1.0.27
/usr/lib64/sane/libsane-artec_eplus48u.so
/usr/lib64/sane/libsane-artec_eplus48u.so.1
/usr/lib64/sane/libsane-artec_eplus48u.so.1.0.27
/usr/lib64/sane/libsane-as6e.so
/usr/lib64/sane/libsane-as6e.so.1
/usr/lib64/sane/libsane-as6e.so.1.0.27
/usr/lib64/sane/libsane-avision.so
/usr/lib64/sane/libsane-avision.so.1
/usr/lib64/sane/libsane-avision.so.1.0.27
/usr/lib64/sane/libsane-bh.so
/usr/lib64/sane/libsane-bh.so.1
/usr/lib64/sane/libsane-bh.so.1.0.27
/usr/lib64/sane/libsane-canon.so
/usr/lib64/sane/libsane-canon.so.1
/usr/lib64/sane/libsane-canon.so.1.0.27
/usr/lib64/sane/libsane-canon630u.so
/usr/lib64/sane/libsane-canon630u.so.1
/usr/lib64/sane/libsane-canon630u.so.1.0.27
/usr/lib64/sane/libsane-canon_dr.so
/usr/lib64/sane/libsane-canon_dr.so.1
/usr/lib64/sane/libsane-canon_dr.so.1.0.27
/usr/lib64/sane/libsane-cardscan.so
/usr/lib64/sane/libsane-cardscan.so.1
/usr/lib64/sane/libsane-cardscan.so.1.0.27
/usr/lib64/sane/libsane-coolscan.so
/usr/lib64/sane/libsane-coolscan.so.1
/usr/lib64/sane/libsane-coolscan.so.1.0.27
/usr/lib64/sane/libsane-coolscan2.so
/usr/lib64/sane/libsane-coolscan2.so.1
/usr/lib64/sane/libsane-coolscan2.so.1.0.27
/usr/lib64/sane/libsane-coolscan3.so
/usr/lib64/sane/libsane-coolscan3.so.1
/usr/lib64/sane/libsane-coolscan3.so.1.0.27
/usr/lib64/sane/libsane-dc210.so
/usr/lib64/sane/libsane-dc210.so.1
/usr/lib64/sane/libsane-dc210.so.1.0.27
/usr/lib64/sane/libsane-dc240.so
/usr/lib64/sane/libsane-dc240.so.1
/usr/lib64/sane/libsane-dc240.so.1.0.27
/usr/lib64/sane/libsane-dc25.so
/usr/lib64/sane/libsane-dc25.so.1
/usr/lib64/sane/libsane-dc25.so.1.0.27
/usr/lib64/sane/libsane-dll.so
/usr/lib64/sane/libsane-dll.so.1
/usr/lib64/sane/libsane-dll.so.1.0.27
/usr/lib64/sane/libsane-dmc.so
/usr/lib64/sane/libsane-dmc.so.1
/usr/lib64/sane/libsane-dmc.so.1.0.27
/usr/lib64/sane/libsane-epjitsu.so
/usr/lib64/sane/libsane-epjitsu.so.1
/usr/lib64/sane/libsane-epjitsu.so.1.0.27
/usr/lib64/sane/libsane-epson.so
/usr/lib64/sane/libsane-epson.so.1
/usr/lib64/sane/libsane-epson.so.1.0.27
/usr/lib64/sane/libsane-epson2.so
/usr/lib64/sane/libsane-epson2.so.1
/usr/lib64/sane/libsane-epson2.so.1.0.27
/usr/lib64/sane/libsane-epsonds.so
/usr/lib64/sane/libsane-epsonds.so.1
/usr/lib64/sane/libsane-epsonds.so.1.0.27
/usr/lib64/sane/libsane-fujitsu.so
/usr/lib64/sane/libsane-fujitsu.so.1
/usr/lib64/sane/libsane-fujitsu.so.1.0.27
/usr/lib64/sane/libsane-genesys.so
/usr/lib64/sane/libsane-genesys.so.1
/usr/lib64/sane/libsane-genesys.so.1.0.27
/usr/lib64/sane/libsane-gt68xx.so
/usr/lib64/sane/libsane-gt68xx.so.1
/usr/lib64/sane/libsane-gt68xx.so.1.0.27
/usr/lib64/sane/libsane-hp.so
/usr/lib64/sane/libsane-hp.so.1
/usr/lib64/sane/libsane-hp.so.1.0.27
/usr/lib64/sane/libsane-hp3500.so
/usr/lib64/sane/libsane-hp3500.so.1
/usr/lib64/sane/libsane-hp3500.so.1.0.27
/usr/lib64/sane/libsane-hp3900.so
/usr/lib64/sane/libsane-hp3900.so.1
/usr/lib64/sane/libsane-hp3900.so.1.0.27
/usr/lib64/sane/libsane-hp4200.so
/usr/lib64/sane/libsane-hp4200.so.1
/usr/lib64/sane/libsane-hp4200.so.1.0.27
/usr/lib64/sane/libsane-hp5400.so
/usr/lib64/sane/libsane-hp5400.so.1
/usr/lib64/sane/libsane-hp5400.so.1.0.27
/usr/lib64/sane/libsane-hp5590.so
/usr/lib64/sane/libsane-hp5590.so.1
/usr/lib64/sane/libsane-hp5590.so.1.0.27
/usr/lib64/sane/libsane-hpljm1005.so
/usr/lib64/sane/libsane-hpljm1005.so.1
/usr/lib64/sane/libsane-hpljm1005.so.1.0.27
/usr/lib64/sane/libsane-hs2p.so
/usr/lib64/sane/libsane-hs2p.so.1
/usr/lib64/sane/libsane-hs2p.so.1.0.27
/usr/lib64/sane/libsane-ibm.so
/usr/lib64/sane/libsane-ibm.so.1
/usr/lib64/sane/libsane-ibm.so.1.0.27
/usr/lib64/sane/libsane-kodak.so
/usr/lib64/sane/libsane-kodak.so.1
/usr/lib64/sane/libsane-kodak.so.1.0.27
/usr/lib64/sane/libsane-kodakaio.so
/usr/lib64/sane/libsane-kodakaio.so.1
/usr/lib64/sane/libsane-kodakaio.so.1.0.27
/usr/lib64/sane/libsane-kvs1025.so
/usr/lib64/sane/libsane-kvs1025.so.1
/usr/lib64/sane/libsane-kvs1025.so.1.0.27
/usr/lib64/sane/libsane-kvs20xx.so
/usr/lib64/sane/libsane-kvs20xx.so.1
/usr/lib64/sane/libsane-kvs20xx.so.1.0.27
/usr/lib64/sane/libsane-kvs40xx.so
/usr/lib64/sane/libsane-kvs40xx.so.1
/usr/lib64/sane/libsane-kvs40xx.so.1.0.27
/usr/lib64/sane/libsane-leo.so
/usr/lib64/sane/libsane-leo.so.1
/usr/lib64/sane/libsane-leo.so.1.0.27
/usr/lib64/sane/libsane-lexmark.so
/usr/lib64/sane/libsane-lexmark.so.1
/usr/lib64/sane/libsane-lexmark.so.1.0.27
/usr/lib64/sane/libsane-ma1509.so
/usr/lib64/sane/libsane-ma1509.so.1
/usr/lib64/sane/libsane-ma1509.so.1.0.27
/usr/lib64/sane/libsane-magicolor.so
/usr/lib64/sane/libsane-magicolor.so.1
/usr/lib64/sane/libsane-magicolor.so.1.0.27
/usr/lib64/sane/libsane-matsushita.so
/usr/lib64/sane/libsane-matsushita.so.1
/usr/lib64/sane/libsane-matsushita.so.1.0.27
/usr/lib64/sane/libsane-microtek.so
/usr/lib64/sane/libsane-microtek.so.1
/usr/lib64/sane/libsane-microtek.so.1.0.27
/usr/lib64/sane/libsane-microtek2.so
/usr/lib64/sane/libsane-microtek2.so.1
/usr/lib64/sane/libsane-microtek2.so.1.0.27
/usr/lib64/sane/libsane-mustek.so
/usr/lib64/sane/libsane-mustek.so.1
/usr/lib64/sane/libsane-mustek.so.1.0.27
/usr/lib64/sane/libsane-mustek_usb.so
/usr/lib64/sane/libsane-mustek_usb.so.1
/usr/lib64/sane/libsane-mustek_usb.so.1.0.27
/usr/lib64/sane/libsane-mustek_usb2.so
/usr/lib64/sane/libsane-mustek_usb2.so.1
/usr/lib64/sane/libsane-mustek_usb2.so.1.0.27
/usr/lib64/sane/libsane-nec.so
/usr/lib64/sane/libsane-nec.so.1
/usr/lib64/sane/libsane-nec.so.1.0.27
/usr/lib64/sane/libsane-net.so
/usr/lib64/sane/libsane-net.so.1
/usr/lib64/sane/libsane-net.so.1.0.27
/usr/lib64/sane/libsane-niash.so
/usr/lib64/sane/libsane-niash.so.1
/usr/lib64/sane/libsane-niash.so.1.0.27
/usr/lib64/sane/libsane-p5.so
/usr/lib64/sane/libsane-p5.so.1
/usr/lib64/sane/libsane-p5.so.1.0.27
/usr/lib64/sane/libsane-pie.so
/usr/lib64/sane/libsane-pie.so.1
/usr/lib64/sane/libsane-pie.so.1.0.27
/usr/lib64/sane/libsane-pieusb.so
/usr/lib64/sane/libsane-pieusb.so.1
/usr/lib64/sane/libsane-pieusb.so.1.0.27
/usr/lib64/sane/libsane-pixma.so
/usr/lib64/sane/libsane-pixma.so.1
/usr/lib64/sane/libsane-pixma.so.1.0.27
/usr/lib64/sane/libsane-plustek.so
/usr/lib64/sane/libsane-plustek.so.1
/usr/lib64/sane/libsane-plustek.so.1.0.27
/usr/lib64/sane/libsane-plustek_pp.so
/usr/lib64/sane/libsane-plustek_pp.so.1
/usr/lib64/sane/libsane-plustek_pp.so.1.0.27
/usr/lib64/sane/libsane-qcam.so
/usr/lib64/sane/libsane-qcam.so.1
/usr/lib64/sane/libsane-qcam.so.1.0.27
/usr/lib64/sane/libsane-ricoh.so
/usr/lib64/sane/libsane-ricoh.so.1
/usr/lib64/sane/libsane-ricoh.so.1.0.27
/usr/lib64/sane/libsane-rts8891.so
/usr/lib64/sane/libsane-rts8891.so.1
/usr/lib64/sane/libsane-rts8891.so.1.0.27
/usr/lib64/sane/libsane-s9036.so
/usr/lib64/sane/libsane-s9036.so.1
/usr/lib64/sane/libsane-s9036.so.1.0.27
/usr/lib64/sane/libsane-sceptre.so
/usr/lib64/sane/libsane-sceptre.so.1
/usr/lib64/sane/libsane-sceptre.so.1.0.27
/usr/lib64/sane/libsane-sharp.so
/usr/lib64/sane/libsane-sharp.so.1
/usr/lib64/sane/libsane-sharp.so.1.0.27
/usr/lib64/sane/libsane-sm3600.so
/usr/lib64/sane/libsane-sm3600.so.1
/usr/lib64/sane/libsane-sm3600.so.1.0.27
/usr/lib64/sane/libsane-sm3840.so
/usr/lib64/sane/libsane-sm3840.so.1
/usr/lib64/sane/libsane-sm3840.so.1.0.27
/usr/lib64/sane/libsane-snapscan.so
/usr/lib64/sane/libsane-snapscan.so.1
/usr/lib64/sane/libsane-snapscan.so.1.0.27
/usr/lib64/sane/libsane-sp15c.so
/usr/lib64/sane/libsane-sp15c.so.1
/usr/lib64/sane/libsane-sp15c.so.1.0.27
/usr/lib64/sane/libsane-st400.so
/usr/lib64/sane/libsane-st400.so.1
/usr/lib64/sane/libsane-st400.so.1.0.27
/usr/lib64/sane/libsane-stv680.so
/usr/lib64/sane/libsane-stv680.so.1
/usr/lib64/sane/libsane-stv680.so.1.0.27
/usr/lib64/sane/libsane-tamarack.so
/usr/lib64/sane/libsane-tamarack.so.1
/usr/lib64/sane/libsane-tamarack.so.1.0.27
/usr/lib64/sane/libsane-teco1.so
/usr/lib64/sane/libsane-teco1.so.1
/usr/lib64/sane/libsane-teco1.so.1.0.27
/usr/lib64/sane/libsane-teco2.so
/usr/lib64/sane/libsane-teco2.so.1
/usr/lib64/sane/libsane-teco2.so.1.0.27
/usr/lib64/sane/libsane-teco3.so
/usr/lib64/sane/libsane-teco3.so.1
/usr/lib64/sane/libsane-teco3.so.1.0.27
/usr/lib64/sane/libsane-test.so
/usr/lib64/sane/libsane-test.so.1
/usr/lib64/sane/libsane-test.so.1.0.27
/usr/lib64/sane/libsane-u12.so
/usr/lib64/sane/libsane-u12.so.1
/usr/lib64/sane/libsane-u12.so.1.0.27
/usr/lib64/sane/libsane-umax.so
/usr/lib64/sane/libsane-umax.so.1
/usr/lib64/sane/libsane-umax.so.1.0.27
/usr/lib64/sane/libsane-umax1220u.so
/usr/lib64/sane/libsane-umax1220u.so.1
/usr/lib64/sane/libsane-umax1220u.so.1.0.27
/usr/lib64/sane/libsane-umax_pp.so
/usr/lib64/sane/libsane-umax_pp.so.1
/usr/lib64/sane/libsane-umax_pp.so.1.0.27
/usr/lib64/sane/libsane-v4l.so
/usr/lib64/sane/libsane-v4l.so.1
/usr/lib64/sane/libsane-v4l.so.1.0.27
/usr/lib64/sane/libsane-xerox_mfp.so
/usr/lib64/sane/libsane-xerox_mfp.so.1
/usr/lib64/sane/libsane-xerox_mfp.so.1.0.27

%files locales -f sane-backends.lang
%defattr(-,root,root,-)

